#### Write a function so that the columns of the output matrix are powers of the input vector.
#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
#### HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [1]:
import numpy as np

In [7]:
x=np.array([1,2,3,4,5])
n=len(x)
np.column_stack([x**(n-1-i) for i in range(n)])


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [8]:
np.vander(x,n)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

**Problem Statement 2:**

**Given a sequence of n values x1, x2, ..., xn and a window size k>0,
the k-th moving average of the given sequence is defined as follows:**

**The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below**

i 1 2 3 4 5 6 7 8 9 10<br>
===== == == == == == == == == == ==<br>
Input 10 20 30 40 50 60 70 80 90 100<br>
y1 25 = (10+20+30+40)/4<br>
y2 35 = (20+30+40+50)/4<br>
y3 45 = (30+40+50+60)/4<br>
y4 55 = (40+50+60+70)/4<br>
y5 65 = (50+60+70+80)/4<br>
y6 75 = (60+70+80+90)/4<br>
y7 85 = (70+80+90+100)/4<br>

**Thus, the moving average sequence has n-k+1=10-4+1=7 values.**

**Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3**



In [19]:
def moving_average(x, w):
    xcsum=np.cumsum(x)
    xcsum[w:]=xcsum[w:] - xcsum[:-w]
    return xcsum[w-1:]/w
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
a_array=np.array(a)
np.array(moving_average(a_array,3)).round(3)

array([  5.   ,   4.667,   5.667,   6.667,   9.667,  28.667,  49.333,
        72.667,  84.   ,  93.333, 116.333])